Repository dymensionxyz/dymint, pull requests merged in 2025-02, with the labels that each got.

#1337 fix(celestia): don't wait for DA readiness to start the sequencer
  .mockery.yaml
  block/manager.go
  block/modes.go
  block/slvalidator_test.go
  da/avail/avail.go
  da/celestia/celestia.go
  da/celestia/celestia_test.go
  da/celestia/client/client.go
  da/celestia/client/errors.go
  da/celestia/client/headers.go
  da/celestia/client/types.go
  da/celestia/config.go
  da/celestia/config_test.go
  da/celestia/mock/messages.go
  da/celestia/mock/server.go
  da/celestia/namespace.go
  da/celestia/rpc.go
  da/celestia/rpc_test.go
  da/celestia/types/rpc.go
  da/celestia/types/types.go
  da/da.go
  da/errors.go
  da/grpc/grpc.go
  da/local/local.go
  da/stub/stub.go
  da/weavevm/wvm.go
  go.mod
  go.sum
  mocks/github.com/dymensionxyz/dymint/block/mock_ExecutorI.go
  mocks/github.com/dymensionxyz/dymint/block/mock_FraudHandler.go
  mocks/github.com/dymensionxyz/dymint/da/avail/mock_SubstrateApiI.go
  mocks/github.com/dymensionxyz/dymint/da/celestia/client/mock_DAClient.go
  mocks/github.com/dymensionxyz/dymint/da/celestia/types/mock_CelestiaRPCClient.go
  mocks/github.com/dymensionxyz/dymint/da/mock_DataAvailabilityLayerClient.go
  mocks/github.com/dymensionxyz/dymint/p2p/mock_StateGetter.go
  mocks/github.com/dymensionxyz/dymint/settlement/dymension/mock_CosmosClient.go
  mocks/github.com/dymensionxyz/dymint/settlement/mock_ClientI.go
  mocks/github.com/dymensionxyz/dymint/store/mock_Store.go
  mocks/github.com/dymensionxyz/dymint/types/pb/dymensionxyz/dymension/rollapp/mock_QueryClient.go
  mocks/github.com/dymensionxyz/dymint/types/pb/dymensionxyz/dymension/sequencer/mock_QueryClient.go
  mocks/github.com/tendermint/tendermint/abci/types/mock_Application.go
  mocks/github.com/tendermint/tendermint/proxy/mock_AppConnConsensus.go
  mocks/github.com/tendermint/tendermint/proxy/mock_AppConns.go
  testutil/mocks.go
Labels: dym-internal

#1355 core(da): da path and metadata refactor
  block/fraud_test.go
  block/manager_test.go
  block/retriever.go
  block/slvalidator.go
  block/slvalidator_test.go
  da/avail/avail.go
  da/avail/avail_test.go
  da/celestia/celestia.go
  da/celestia/celestia_test.go
  da/celestia/metadata.go
  da/da.go
  da/da_test.go
  da/grpc/grpc.go
  da/grpc/mockserv/mockserv.go
  da/local/local.go
  da/stub/stub.go
  da/weavevm/metadata.go
  da/weavevm/wvm.go
  da/weavevm/wvm_test.go
  settlement/dymension/dymension_test.go
  settlement/dymension/utils.go
  settlement/grpc/grpc.go
  settlement/local/local.go
  settlement/settlement.go
  testutil/mocks.go
  types/block_source.go
  types/errors.go
Labels: dym-internal

#1353 Typo fix CHANGELOG.md
  CHANGELOG.md
Labels: Stale

#1351 Fix typo prefix_test.go
  store/prefix_test.go
Labels: Stale

#1348 report.go
  test/loadtime/report/report.go
Labels: Stale

#1350 sequencers_test.go
  block/sequencers_test.go
Labels: Stale

#1352 fix typo ws_test.go
  rpc/json/ws_test.go
Labels: Stale

#1368 feat(da): enable da rotation
  block/balance.go
  block/block.go
  block/fraud_test.go
  block/manager.go
  block/manager_test.go
  block/production_test.go
  block/pruning_test.go
  block/retriever.go
  block/slvalidator.go
  block/slvalidator_test.go
  block/submit.go
  block/submit_test.go
  config/config.go
  config/config_test.go
  config/flags.go
  da/celestia/celestia.go
  da/celestia/metadata.go
  da/da.go
  da/stub/stub.go
  da/weavevm/metadata.go
  da/weavevm/wvm.go
  mocks/github.com/dymensionxyz/dymint/da/mock_DataAvailabilityLayerClient.go
  mocks/github.com/dymensionxyz/dymint/store/mock_Store.go
  node/node.go
  node/node_test.go
  rpc/client/client.go
  rpc/client/client_test.go
  rpc/json/service_test.go
  store/store.go
  store/storeIface.go
  testutil/block.go
  testutil/node.go
  types/errors.go
  types/rollapp_params.go
  types/state.go
Labels: C:da, dym-internal

#1357 feat(da): improvements in avail da with availability check
  .mockery.yaml
  block/retriever.go
  block/slvalidator.go
  block/slvalidator_test.go
  config/toml.go
  da/avail/avail.go
  da/avail/avail_test.go
  da/avail/client.go
  da/errors.go
  go.mod
  go.sum
  mocks/github.com/dymensionxyz/dymint/da/avail/mock_AvailClient.go
  mocks/github.com/dymensionxyz/dymint/da/avail/mock_SubstrateApiI.go
  types/errors.go
Labels: C:da, dym-internal

#1371 fix(weavevm): avoid false positive availability check
  da/weavevm/wvm.go
  da/weavevm/wvm_test.go
Labels: dym-internal

#1376 feat(da): added config defaults for supported da
  .golangci.yml
  config/toml.go
Labels: dym-internal

#1378 chore: bump golang to 1.24.0-alpine3.21 in Dockerfile
  Dockerfile
Labels: dym-internal

#1380 fix(comet rpc): fix blockchain info range filter
  rpc/client/client.go
  rpc/client/clientq_test.go
Labels: dym-internal
